### ISSUE TITLE
Stories always output "<0x0A>" 

### ISSUE THREAD

**Issue by DannyAn** [mukel/llama2.java#2]
% java --enable-preview --add-modules=jdk.incubator.vector Llama2 stories15M.bin
WARNING: Using incubator modules: jdk.incubator.vector
Config{dim=288, hidden_dim=768, n_layers=6, n_heads=6, n_kv_heads=6, vocab_size=32000, seq_len=256, shared_weights=true, head_size=48}
Once upon a time, there was a little girl named Lily. She loved to play in her backyard, but there was a big fence that surrounded her home. One day, Lily's mom asked her to clean the fence. Lily didn't want to, but she knew it was important to help her mom.<0x0A>As she was cleaning, Lily found an old key hidden in the grass. She picked it up and showed it to her mom. "Look, Mommy! I found this key! Can we use it to open this fence?" Lily asked. <0x0A>Her mom looked at the fence and said, "That's a fake fence, Lily. It's not used to playing in our backyard. But we can use it to build a fence around it."<0x0A>Lily was happy to hear that they could use the fake fence instead. She ran to get her toys and started playing with them. From that day on, Lily made sure to always check that the fake fence was the right thing to do.

achieved tok/s: 63.073076

**Comment by mukel** [comment]
Fixed in d39d72b , llama2.c was updated to handle UTF-8; you need to update your [tokenizer.bin](https://github.com/karpathy/llama2.c/raw/master/tokenizer.bin) as well.
